name: Webpage Change Monitor
on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  check-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run monitor script
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python monitor.py

      - name: Upload page hash file
        uses: actions/upload-artifact@v3
        with:
          name: webpage_content
          path: webpage_content.txt
        
      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git webpage_content.txt
          git commit -m 'Update page hash'
          git push
